version: '3'

networks:
  default:
    external:
      name: network

services:

  traefik:
    container_name: traefik
    image: traefik
    restart: always
    environment:
      - TZ=Europe/Moscow
    command:
      - --accesslog.fields.names.StartUTC=drop
      - --providers.docker
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/traefik.yaml
      - ./acme.json:/acme.json
      - ./traefik.log:/var/log/traefik.log
    labels:
      - traefik.enable=false
