entryPoints:

  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: resolver

certificatesResolvers:
  resolver:
    acme:
      email: katunin.pavel@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    network: network
